routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('welcome');

Auth::routes();

// All routes in this group are protected by the auth middleware
Route::middleware(['auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('categories', 'CategoriesController');
    Route::resource('posts', 'PostsController')->middleware('auth');

    Route::resource('tags', 'TagsController');

    Route::get('trashed-posts', 'PostsController@trashed')->name('trashed-posts.index'); //name() gives a route name, so in the blade files you go to a route via the route names with route() instead of the route itself. To check all route names 'art route:list'

    Route::put('restore-post/{post}', 'PostsController@restore')->name('restore-post');
});

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $fillable = [
        'name'
    ];

    public function posts()
    {
        return $this->belongsToMany(Post::class);
    }
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use App\Tag;
use Illuminate\Http\Request;
use App\Http\Requests\Tags\CreateTagRequest;
use App\Http\Requests\Tags\UpdateTagRequest;

class TagsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('tags.index')->with('tags', Tag::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateTagRequest $request)
    {
        Tag::create([
            'name' => $request->name
        ]);

        session()->flash('success', 'Tag Created Successfully!');

        return redirect(route('tags.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        return view('tags.create')->with('tag', $tag);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTagRequest $request, Tag $tag)
    {
        $tag->update([
            'name' => $request->name
        ]);

        session()->flash('success', 'Tag Edited Successfully!');

        return redirect(route('tags.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        $tag->delete();

        session()->flash('success', 'Tag Deleted Successfully!');

        return redirect(route('tags.index'));
    }
}

resources/views/tags/create.blade.php
@extends('layouts.app')

@section('content')

<div class="card card-default">
    <div class="card-header">
        {{ isset($tag) ? 'Edit Tag' : 'Create Tag' }}
    </div>
    <div class="card-body">
        @include('partials.errors')
        <form action="{{ isset($tag) ? route('tags.update', $tag->id) : route('tags.store') }}" method="POST">
            @csrf

            @if(isset($tag))
            @method('PUT')
            @endif
            <div class="form-group">
                <label for="name"> Name</label>
                <input type="text" id="name" class="form-control" name="name" value="{{ isset($tag) ? $tag->name : '' }}">
            </div>

            <div class="form-group">
                <button class="btn btn-success">{{ isset($tag) ? 'Update Tag' : 'Add Tag' }}</button>
            </div>
        </form>
    </div>
</div>

@endsection

resources/views/tags/index.blade.php
@extends('layouts.app')

@section('content')

<div class="card card-default">
    <div class="card-header">Tags</div>
    <div class="card-body">
        @if($tags->count() > 0)

        <div class="d-flex justify-content-end mb-2">
            <a href="{{ route('tags.create') }}" class="btn btn-success float-right">Add Tag</a>
        </div>

        <table class="table">
            <thead>
                <th scope="col">Name</th>
                <th scope="col">Posts Count</th>
                <th scope="col"></th>
            </thead>

            <tbody>
                @foreach($tags as $tag)
                <tr scope="row">
                    <td>
                        {{ $tag->name }}
                    </td>

                    <td>
                        {{ $tag->posts->count() }}
                    </td>

                    <td class="float-right">
                        <button class="btn btn-danger btn-sm" onclick="handleDelete({{ $tag->id }})">Delete</button>
                    </td>
                    <td class="float-right">
                        <a href="{{ route('tags.edit', $tag->id) }}" class="btn btn-info btn-sm">Edit</a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <form action="" method="POST" id="deleteTagForm">
            @csrf
            @method('DELETE')

            <!-- Modal -->
            <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Delete Tag</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p class="text-center text-bold">Are you sure you want to delete this tag?</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">No, Return</button>
                            <button type="submit" class="btn btn-danger">Yes, Delete</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        @else
        <h1 class="text-center display-5 m-3 mb-5">No Tag Created</h1>

        <div class="d-flex justify-content-end mb-2">
            <a href="{{ route('tags.create') }}" class="btn btn-success float-right">Add Tag</a>
        </div>
        @endif

    </div>
</div>

@endsection

@section('scripts')

<script>
    const handleDelete = (id) => {

        let form = document.getElementById('deleteTagForm');
        form.action = `/tags/${id}`;

        $('#deleteModal').modal('show');

    };
</script>
@endsection