routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index')->name('welcome');

Auth::routes();

// All routes in this group are protected by the auth middleware
Route::middleware(['auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('categories', 'CategoriesController');
    Route::resource('posts', 'PostsController')->middleware('auth');

    Route::resource('tags', 'TagsController');

    Route::get('trashed-posts', 'PostsController@trashed')->name('trashed-posts.index'); //name() gives a route name, so in the blade files you go to a route via the route names with route() instead of the route itself. To check all route names 'art route:list'

    Route::put('restore-post/{post}', 'PostsController@restore')->name('restore-post');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use Illuminate\Database\Eloquent\SoftDeletes;
use CyrildeWit\EloquentViewable\Contracts\Viewable;
use CyrildeWit\EloquentViewable\InteractsWithViews;

class Post extends Model implements Viewable
{
    use SoftDeletes;
    use InteractsWithViews;

    protected $fillable = [
        'title', 'description', 'content', 'image', 'published_at', 'category_id'
    ];

    
    /**
     * Delete post image from storage
     * 
     * @return void
     */

    public function deleteImage()
    {
        Storage::delete($this->image);
    }

    // RELATIONSHIPS
    // NOTE category IS THE NAME OF THE MODEL TO WHICH THE POST BELONGS TO IN LOWER CASE
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    /**
     * Check if post has a tag
     * 
     * @return bool
     */


    public function hasTag($tagId)
    {
        return in_array($tagId, $this->tags->pluck('id')->toArray());
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use visits;
use App\Tag;
use App\Post;
use App\Category;
use Illuminate\Http\Request;
use App\Http\Requests\Post\UpdatePostRequest;
use App\Http\Requests\Post\CreatePostsRequest;

class PostsController extends Controller
{

    public function __construct()
    {
        // apply the verifyCategoriesCount middleware only on the create and store routes for this resourceful controller
        $this->middleware('verifyCategoriesCount')->only(['create', 'store']);
    }



    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $post = new Post;
        // $visits = Post::with('visits')->get(); 
        return view('posts.index')->with('posts', Post::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create')->with('categories', Category::all())->with('tags', Tag::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreatePostsRequest $request)
    {
        // Upload the image 

        // dd($request->image->store('posts')); //this generates the path to the stored uploaded image. posts is the folder where the file is stored. check file in storage/app/posts

        $image = $request->image->store('posts');

        // Create post
        $post = Post::create([
            'title' => $request->title,
            'description' => $request->description,
            'content' => $request->content,
            'published_at' => $request->published_at,
            'category_id' => $request->category,
            'image' => $image //path to the image
        ]);

        if ($request->tags) {
            $post->tags()->attach($request->tags); //the attach is used for the many to many relationship. It will attach the tags selected on the frontend with the newly created post
        }

        // Flash success message
        session()->flash('success', 'Post Created Successfully!');

        // Redirect user
        return redirect(route('posts.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        views($post)->record();

        return view('posts.show')->with('post', $post)->with('categories', Category::all())->with('tags', Tag::all());
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        // dd($post->tags->pluck('id')->toArray());

        return view('posts.create')->with('post', $post)->with('categories', Category::all())->with('tags', Tag::all());
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePostRequest $request, Post $post)
    {
        $data = $request->only(['title', 'description', 'published_at', 'content']);

        // check for new image
        if ($request->hasFile('image')) {
            // upload it
            $image = $request->image->store('posts');

            // delete old image
            // Storage::delete($post->image);
            $post->deleteImage();

            $data['image'] = $image;
        }

        if ($request->tags) {
            $post->tags()->sync($request->tags); //this will check for any new incoming tags and attach them to the post. If a current tag already associated with the post wasn't selected when editing (updating), then it detaches from the post.
        }

        // update attributes
        $post->update($data);

        // flash message
        session()->flash('success', 'Post Updated Successfully');

        // redirect user
        return redirect(route('posts.index'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //This would be used instead of route model binding because route model binding wouldn't find a soft deleted post
        $post = Post::withTrashed()->where('id', $id)->firstOrFail();

        if ($post->trashed()) {
            // Delete Post Image
            // Storage::delete($post->image);
            $post->deleteImage();
            //remember $post->image is the path to the image location

            //Delete Post
            $post->forceDelete();

            // Flash success message
            session()->flash('success', 'Post Deleted Successfully!');
        } else {
            $post->delete();

            // Flash success message
            session()->flash('success', 'Post Trashed Successfully!');
        }

        // Redirect user
        return redirect(route('posts.index'));
    }


    /**
     * Displays a list of all trashed posts.
     *
     * @return \Illuminate\Http\Response
     */
    public function trashed()
    {
        // $trashed = Post::withTrashed()->get();//withTrashed shows all including trashed
        $trashed = Post::onlyTrashed()->get();

        return view('posts.index')->withPosts($trashed); //same as with('posts', $trashed)
    }

    /**
     * Restores a trashed post.
     *
     *
     */

    public function restore($id)
    {
        $post = Post::withTrashed()->where('id', $id)->firstOrFail();

        $post->restore();

        session()->flash('success', 'Post Restored Successfully!');

        return redirect()->back();
    }

}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('css')
<!-- DATEPICKER -FLATPICKR -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

<!-- MULTI SELECT TOOL -SELECT2 -->
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
@endsection

@section('content')

<div class="card card-default">
    <div class="card-header">
        {{ isset($post) ? 'Edit Post' : 'Create Post' }}
    </div>
    <div class="card-body">
        @include('partials.errors')
        <form action="{{ isset($post) ? route('posts.update', $post->id) : route('posts.store') }}" method="POST" enctype="multipart/form-data">
            @csrf

            @if(isset($post))
            @method('PUT')
            @endif
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" id="title" class="form-control" name="title" value="{{ isset($post) ? $post->title : '' }}">
            </div>

            <div class="form-group">
                <label for="description">Description</label>
                <textarea name="description" id="description" cols="5" rows="5" class="form-control">{{ isset($post) ? $post->description : '' }}</textarea>
            </div>

            <div class="form-group">
                <label for="content">Content</label>
                <input id="content" type="hidden" name="content" value="{{ isset($post) ? $post->content : '' }}" />
                <trix-editor input="content"></trix-editor>
            </div>

            <div class="form-group">
                <label for="published_at">Published At</label>
                <input type="text" id="published_at" class="form-control" name="published_at" value="{{ isset($post) ? $post->published_at : '' }}">
            </div>

            <!-- <div class="form-group">
                </div> -->
            <div class="form-group">
                <label for="image">Image</label>
                @if(isset($post))
                <img src="{{ asset('storage/'.$post->image) }}" alt="post image" style="width: 100%">
                @endif

                <input type="file" id="image" class="form-control" name="image">
            </div>

            <div class="form-group">
                <label for="category">Category</label>
                <select class="form-control" name="category" id="category">
                    @if(isset($post))

                    @foreach($categories as $category)
                    <option value="{{ $category->id }}" @if($category->id === $post->category_id)
                        selected
                        @endif
                        >{{ $category->name }}</option>
                    @endforeach

                    @else
                    @foreach($categories as $category)
                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                    @endforeach

                    @endif
                </select>
            </div>
            @if($tags->count() > 0)
            <div class="form-group">
                <label for="tags">Tags</label>
                {{-- [] is used because it is a multiselect input, and the selected options have to be passed as an array, else only one would be in the request body--}}
                <select name="tags[]" id="tags" class="form-control tags-selector" multiple>

                    @foreach($tags as $tag)

                    <option value="{{ $tag->id }}"
                        @if(isset($post)) 
                            @if($post->hasTag($tag->id))
                                selected
                            @endif
                        @endif
                    >{{ $tag->name }}</option>

                    @endforeach

                </select>
            </div>
            @endif

            <div class="form-group">
                <button class="btn btn-success">{{ isset($post) ? 'Update Post' : 'Add Post' }}</button>
            </div>
        </form>
    </div>
</div>

@endsection

@section('scripts')
<!-- DATEPICKER -->
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

<script>
    flatpickr('#published_at', {
        enableTime: true
    })
</script>

<!-- MULTI SELECT TOOL -SELECT2 -->
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>

<script>
    $(document).ready(() => {
        $(".tags-selector").select2({
            tags: true
        });
    })
</script>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')

<div class="card card-default">
    <div class="card-header">Posts</div>
    <div class="card-body">
        @if($posts->count() > 0)
        <div class="d-flex justify-content-end mb-2">
            <a href="{{ route('posts.create') }}" class="btn btn-success float-right">Add Posts</a>
        </div>

        <table class="table">
            <thead>
                <th scope="col">Image</th>
                <th scope="col">Title</th>
                <th scope="col">Category</th>
                <th></th>
            </thead>

            <tbody>
                @foreach($posts as $post)
                <tr scope="row">
                    <td>
                        <img src="{{ asset('storage/'.$post->image) }}" alt="img" width="120px" height="60px">
                    </td>

                    <td>
                        {{ $post->title }}
                    </td>

                    <td>
                        <a href="{{ route('categories.edit', $post->category->id) }}">{{ $post->category->name }}</a>
                    </td>

                    <td scope="row" class="">
                        <div class="d-flex">
                            @if(!$post->trashed())

                            <a href="{{ route('posts.show', $post->id) }}" class="btn btn-info btn-sm align-self-start mr-4" role="button">View</a>

                            <a href="{{ route('posts.edit', $post->id) }}" class="btn btn-secondary btn-sm align-self-center mx-auto ml-2" role="button">Edit</a>

                            @else

                            <form action="{{ route('restore-post', $post->id) }}" class="float-right ml-auto" method="post" style="display: inline;">
                                @csrf
                                @method('PUT')

                                <button class="btn btn-info btn-sm align-self-end" type="submit">Restore</button>

                            </form>
                            @endif

                        </div>
                    </td>

                    <td class="float-right">
                        <form action="{{ route('posts.destroy', $post->id) }}" method="POST">
                            @csrf
                            @method('DELETE')

                            <button type="submit" class="btn btn-danger btn-sm">
                                {{ $post->trashed() ? 'Delete' : 'Trash' }}
                            </button>

                        </form>
                    </td>

                </tr>
                @endforeach
            </tbody>
        </table>
        @else
        <h1 class="text-center display-5 m-3 mb-5">No Posts At The Moment...</h1>

        <div class="d-flex justify-content-end mb-2">
            <a href="{{ route('posts.create') }}" class="btn btn-success float-right">Add Posts</a>
        </div>

        @endif

    </div>
</div>

@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('content')
<div class="card card-default">
    <div class="card-header">
        {{ isset($post) ? $post->title : '' }}
        <button class="btn btn-primary float-right">
            Post Views: {{ views($post)->count() }} <i class="fa fa-eye"></i>
        </button>
    </div>
    <div class="card-body">
        <form action="#" method="POST" enctype="multipart/form-data">

            <div class="form-group">
                <label for="description">Description</label>
                <textarea name="description" id="description" cols="5" rows="5" class="form-control" disabled>{{ isset($post) ? $post->description : '' }}</textarea>
            </div>

            <div class="form-group">
                <label for="content">Content</label>
                <input id="content" type="hidden" name="content" value="{{ isset($post) ? $post->content : '' }}" disabled />
            </div>

            <div class="form-group">
                <label for="published_at">Published At</label>
                <input type="text" id="published_at" class="form-control" name="published_at" value="{{ isset($post) ? $post->published_at : '' }}" disabled>
            </div>

            <div class="form-group">
                <label for="image">Image</label>
                @if(isset($post))
                <img src="{{ asset('storage/'.$post->image) }}" alt="post image" style="width: 100%">
                @endif
            </div>

            <div class="form-group">
                <label for="category">Category</label>
                <select class="form-control" name="category" id="category" disabled>
                    @if(isset($post))

                    @foreach($categories as $category)
                    <option value="{{ $category->id }}" @if($category->id === $post->category_id)
                        selected
                        @endif
                        >{{ $category->name }}</option>
                    @endforeach

                    @else
                    @foreach($categories as $category)
                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                    @endforeach

                    @endif
                </select>
            </div>
            @if($tags->count() > 0)
            <div class="form-group">
                <label for="tags">Tags</label>
                {{-- [] is used because it is a multiselect input, and the selected options have to be passed as an array, else only one would be in the request body--}}
                <select name="tags[]" id="tags" class="form-control tags-selector" multiple disabled>

                    @foreach($tags as $tag)

                    <option value="{{ $tag->id }}" @if(isset($post)) @if($post->hasTag($tag->id))
                        selected
                        @endif
                        @endif
                        >{{ $tag->name }}</option>

                    @endforeach

                </select>
            </div>
            @endif

        </form>
    </div>
</div>

@endsection